
package online.banking.system;


import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hp
 */
public class Menu extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs;
PreparedStatement st;
    /**
     * Creates new form Menu
     */
    public Menu() {
        super("Home");
        initComponents();
        conn=dbconnect.connectDb();
        Calendar();
        Account();
        Table1();
    }
   //use calendar to set date
    public void Calendar(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        CurrentDate.setText(+ day + "-" + (month+1) + "-" + year);
    }
    
    //list customers in table
    public void Table1()
    {
        try{
            conn=dbconnect.connectDb();
            
            String sql = "select Acc,CustomerID,FName,LName,DOB,Gender,Mob from Account";
            st = conn.prepareStatement(sql);
            rs = st.executeQuery();
            Customers.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                conn.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ProfileTab1 = new javax.swing.JPanel();
        FullnametxtProfile1 = new javax.swing.JLabel();
        DateofbirthtxtProfile1 = new javax.swing.JLabel();
        GendertxtProfile1 = new javax.swing.JLabel();
        EthnicitytxtProfile1 = new javax.swing.JLabel();
        AddresstxtProfile1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        AccnumtxtProfile1 = new javax.swing.JLabel();
        AcctypetxtProfile1 = new javax.swing.JLabel();
        MobiletxtProfile1 = new javax.swing.JLabel();
        Accno = new javax.swing.JTextField();
        CustID = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        EditProfile1 = new javax.swing.JButton();
        SaveProfile1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Balamt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        UnametxtWithdraw = new javax.swing.JLabel();
        UsernameWithdraw = new javax.swing.JTextField();
        SearchWithdraw = new javax.swing.JButton();
        FullnameWithdraw = new javax.swing.JTextField();
        FullnametxtWithdraw = new javax.swing.JLabel();
        AccnumtxtWithdraw = new javax.swing.JLabel();
        AccnumWithdraw = new javax.swing.JTextField();
        BaltxtWithdraw = new javax.swing.JLabel();
        BalWithdraw = new javax.swing.JTextField();
        AmounttxtWithdraw = new javax.swing.JLabel();
        AmountWithdraw = new javax.swing.JTextField();
        NewbaltxtWithdraw = new javax.swing.JLabel();
        NewbalWithdraw = new javax.swing.JTextField();
        CalculateWithdraw = new javax.swing.JButton();
        Withdraw = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        TransferTab = new javax.swing.JPanel();
        UnametxtTransfer = new javax.swing.JLabel();
        FullnametxtTransfer = new javax.swing.JLabel();
        AccnumtxtTransfer = new javax.swing.JLabel();
        BaltxtTransfer = new javax.swing.JLabel();
        AmounttxtTransfer = new javax.swing.JLabel();
        CreditamounttxtTransfer = new javax.swing.JLabel();
        UsernameTransfer = new javax.swing.JTextField();
        FullnameTransfer = new javax.swing.JTextField();
        AccnumTransfer = new javax.swing.JTextField();
        BalTransfer = new javax.swing.JTextField();
        TransferInput = new javax.swing.JTextField();
        NewbalTransfer = new javax.swing.JTextField();
        AccTransfer = new javax.swing.JComboBox();
        TransferNewInput = new javax.swing.JTextField();
        NewbalAccTransfer = new javax.swing.JTextField();
        SearchTransfer = new javax.swing.JButton();
        CalculateTransfer1 = new javax.swing.JButton();
        CalculateTransfer2 = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Customers = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ProfileTab2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UsernameTop = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CurrentDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ProfileTab1.setBackground(new java.awt.Color(204, 204, 255));
        ProfileTab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        FullnametxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FullnametxtProfile1.setText("First Name");

        DateofbirthtxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateofbirthtxtProfile1.setText("DOB");

        GendertxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GendertxtProfile1.setText("Gender");

        EthnicitytxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EthnicitytxtProfile1.setText("CITY");

        AddresstxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddresstxtProfile1.setText("Address");

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(255, 255, 255));

        DOB.setEditable(false);
        DOB.setBackground(new java.awt.Color(255, 255, 255));

        gender.setEditable(false);
        gender.setBackground(new java.awt.Color(255, 255, 255));

        city.setEditable(false);
        city.setBackground(new java.awt.Color(255, 255, 255));

        add.setEditable(false);
        add.setBackground(new java.awt.Color(255, 255, 255));

        AccnumtxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccnumtxtProfile1.setText("Account No.");

        AcctypetxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AcctypetxtProfile1.setText("Customer ID");

        MobiletxtProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MobiletxtProfile1.setText("Mobile");

        Accno.setEditable(false);
        Accno.setBackground(new java.awt.Color(255, 255, 255));

        CustID.setEditable(false);
        CustID.setBackground(new java.awt.Color(255, 255, 255));

        mobile.setEditable(false);
        mobile.setBackground(new java.awt.Color(255, 255, 255));

        EditProfile1.setBackground(new java.awt.Color(0, 0, 255));
        EditProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditProfile1.setForeground(new java.awt.Color(255, 255, 255));
        EditProfile1.setText("Edit");
        EditProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfile1ActionPerformed(evt);
            }
        });

        SaveProfile1.setBackground(new java.awt.Color(0, 0, 255));
        SaveProfile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveProfile1.setForeground(new java.awt.Color(255, 255, 255));
        SaveProfile1.setText("Save");
        SaveProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveProfile1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Balance");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("PIN");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Last Name");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("EMAIL");

        javax.swing.GroupLayout ProfileTab1Layout = new javax.swing.GroupLayout(ProfileTab1);
        ProfileTab1.setLayout(ProfileTab1Layout);
        ProfileTab1Layout.setHorizontalGroup(
            ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileTab1Layout.createSequentialGroup()
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfileTab1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddresstxtProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(AccnumtxtProfile1)
                            .addComponent(FullnametxtProfile1)
                            .addComponent(DateofbirthtxtProfile1)
                            .addComponent(MobiletxtProfile1))
                        .addGap(96, 96, 96)
                        .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EditProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Accno, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Balamt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveProfile1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AcctypetxtProfile1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GendertxtProfile1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EthnicitytxtProfile1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );
        ProfileTab1Layout.setVerticalGroup(
            ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileTab1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccnumtxtProfile1)
                    .addComponent(AcctypetxtProfile1)
                    .addComponent(CustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Balamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullnametxtProfile1)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GendertxtProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateofbirthtxtProfile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobiletxtProfile1))
                .addGap(46, 46, 46)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EthnicitytxtProfile1)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddresstxtProfile1))
                .addGap(40, 40, 40)
                .addGroup(ProfileTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveProfile1)
                    .addComponent(EditProfile1))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfileTab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfileTab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Profiile", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        UnametxtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UnametxtWithdraw.setText("Customer ID");

        UsernameWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SearchWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchWithdraw.setText("Search");
        SearchWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchWithdrawActionPerformed(evt);
            }
        });

        FullnameWithdraw.setEditable(false);
        FullnameWithdraw.setBackground(new java.awt.Color(255, 255, 255));
        FullnameWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        FullnametxtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FullnametxtWithdraw.setText("Name");

        AccnumtxtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccnumtxtWithdraw.setText("Account No.");

        AccnumWithdraw.setEditable(false);
        AccnumWithdraw.setBackground(new java.awt.Color(255, 255, 255));
        AccnumWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BaltxtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BaltxtWithdraw.setText("Available balance");

        BalWithdraw.setEditable(false);
        BalWithdraw.setBackground(new java.awt.Color(255, 255, 255));
        BalWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AmounttxtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AmounttxtWithdraw.setText("Amount");

        AmountWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        NewbaltxtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewbaltxtWithdraw.setText("Total");

        NewbalWithdraw.setEditable(false);
        NewbalWithdraw.setBackground(new java.awt.Color(255, 255, 255));
        NewbalWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CalculateWithdraw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalculateWithdraw.setText("Calculate ");
        CalculateWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateWithdrawActionPerformed(evt);
            }
        });

        Withdraw.setBackground(new java.awt.Color(0, 0, 255));
        Withdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Withdraw.setForeground(new java.awt.Color(255, 255, 255));
        Withdraw.setText("Withdraw");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FullnametxtWithdraw)
                    .addComponent(UnametxtWithdraw)
                    .addComponent(AccnumtxtWithdraw)
                    .addComponent(BaltxtWithdraw)
                    .addComponent(AmounttxtWithdraw)
                    .addComponent(NewbaltxtWithdraw))
                .addGap(93, 93, 93)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewbalWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccnumWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FullnameWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculateWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(489, 489, 489))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnametxtWithdraw)
                    .addComponent(UsernameWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchWithdraw))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullnametxtWithdraw)
                    .addComponent(FullnameWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccnumtxtWithdraw)
                    .addComponent(AccnumWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaltxtWithdraw)
                    .addComponent(BalWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmounttxtWithdraw)
                    .addComponent(AmountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewbaltxtWithdraw)
                    .addComponent(NewbalWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculateWithdraw))
                .addGap(18, 18, 18)
                .addComponent(Withdraw)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Withdraw", jPanel2);

        TransferTab.setBackground(new java.awt.Color(204, 204, 255));
        TransferTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        UnametxtTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UnametxtTransfer.setText("CustomerID");

        FullnametxtTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FullnametxtTransfer.setText("Name");

        AccnumtxtTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccnumtxtTransfer.setText("Account No.");

        BaltxtTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BaltxtTransfer.setText("Available Balance");

        AmounttxtTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AmounttxtTransfer.setText("Transfer Amount");

        CreditamounttxtTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreditamounttxtTransfer.setText("Credit Account");

        FullnameTransfer.setEditable(false);
        FullnameTransfer.setBackground(new java.awt.Color(255, 255, 255));

        AccnumTransfer.setEditable(false);
        AccnumTransfer.setBackground(new java.awt.Color(255, 255, 255));

        BalTransfer.setEditable(false);
        BalTransfer.setBackground(new java.awt.Color(255, 255, 255));

        NewbalTransfer.setEditable(false);
        NewbalTransfer.setBackground(new java.awt.Color(255, 255, 255));

        AccTransfer.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                AccTransferPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        AccTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccTransferActionPerformed(evt);
            }
        });

        TransferNewInput.setEditable(false);
        TransferNewInput.setBackground(new java.awt.Color(255, 255, 255));
        TransferNewInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferNewInputActionPerformed(evt);
            }
        });

        NewbalAccTransfer.setEditable(false);
        NewbalAccTransfer.setBackground(new java.awt.Color(255, 255, 255));
        NewbalAccTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewbalAccTransferActionPerformed(evt);
            }
        });

        SearchTransfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchTransfer.setText("Search");
        SearchTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTransferActionPerformed(evt);
            }
        });

        CalculateTransfer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalculateTransfer1.setText("Calculate");
        CalculateTransfer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateTransfer1ActionPerformed(evt);
            }
        });

        CalculateTransfer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalculateTransfer2.setText("Calculate");
        CalculateTransfer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateTransfer2ActionPerformed(evt);
            }
        });

        Transfer.setBackground(new java.awt.Color(0, 0, 255));
        Transfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Transfer.setForeground(new java.awt.Color(255, 255, 255));
        Transfer.setText("Transfer");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransferTabLayout = new javax.swing.GroupLayout(TransferTab);
        TransferTab.setLayout(TransferTabLayout);
        TransferTabLayout.setHorizontalGroup(
            TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferTabLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UnametxtTransfer)
                    .addComponent(FullnametxtTransfer)
                    .addComponent(AccnumtxtTransfer)
                    .addComponent(BaltxtTransfer)
                    .addComponent(AmounttxtTransfer)
                    .addComponent(CreditamounttxtTransfer))
                .addGap(41, 41, 41)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameTransfer)
                    .addComponent(FullnameTransfer)
                    .addComponent(AccnumTransfer)
                    .addComponent(BalTransfer)
                    .addGroup(TransferTabLayout.createSequentialGroup()
                        .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TransferInput)
                            .addComponent(AccTransfer, 0, 121, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewbalTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addComponent(TransferNewInput))))
                .addGap(18, 18, 18)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TransferTabLayout.createSequentialGroup()
                        .addComponent(NewbalAccTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CalculateTransfer2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CalculateTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        TransferTabLayout.setVerticalGroup(
            TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferTabLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnametxtTransfer)
                    .addComponent(UsernameTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTransfer))
                .addGap(38, 38, 38)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullnametxtTransfer)
                    .addComponent(FullnameTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccnumtxtTransfer)
                    .addGroup(TransferTabLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(AccnumTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaltxtTransfer)
                    .addComponent(BalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmounttxtTransfer)
                    .addComponent(TransferInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewbalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalculateTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CreditamounttxtTransfer)
                        .addComponent(AccTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TransferNewInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NewbalAccTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CalculateTransfer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(Transfer)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TransferTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TransferTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Transfer", jPanel3);

        Customers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Customers);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("CustomerList", jPanel4);

        ProfileTab2.setBackground(new java.awt.Color(204, 204, 255));
        ProfileTab2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setText("AMX BANK");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/banking/images/LOGOM.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setText("AMX Bank is one of the most prestigious BANKs in India.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel19.setText("Founder of Bank Mr.AMAN GUPTA and it's team in 2022 in Meerut.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel20.setText("It is an affilated by RBI (Reserver Bank Of India)");

        javax.swing.GroupLayout ProfileTab2Layout = new javax.swing.GroupLayout(ProfileTab2);
        ProfileTab2.setLayout(ProfileTab2Layout);
        ProfileTab2Layout.setHorizontalGroup(
            ProfileTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileTab2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel17)
                .addGroup(ProfileTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileTab2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel20))
                    .addGroup(ProfileTab2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(ProfileTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)))
                    .addGroup(ProfileTab2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        ProfileTab2Layout.setVerticalGroup(
            ProfileTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileTab2Layout.createSequentialGroup()
                .addGroup(ProfileTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileTab2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileTab2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", ProfileTab2);

        jTabbedPane2.addTab("About", jTabbedPane1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/banking/images/LOGOM.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setText("WELCOME");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("TO");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 102));
        jLabel7.setText("AMX BANK");

        jLabel8.setText("Customer ID:");

        jLabel9.setText("DATE:");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(64, 64, 64)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel6)))
                        .addGap(147, 147, 147)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel7))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UsernameTop, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(CurrentDate))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(UsernameTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(CurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButton1)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfile1ActionPerformed
        gender.setEditable(true);
        email.setEditable(true);
        add.setEditable(true);
        mobile.setEditable(true);
        city.setEditable(true);
        pin.setEditable(true);
        
    }//GEN-LAST:event_EditProfile1ActionPerformed

    private void SaveProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveProfile1ActionPerformed
        try{
            String value1 = gender.getText();
            String value2 = email.getText();
            String value3 = add.getText();
            String value4 = mobile.getText();
            String value5 = city.getText();
            conn=dbconnect.connectDb();
            
            String sql = "UPDATE Account SET Gender='"+value1+"',Email='"+value2+"',Address='"+value3+"',Mob='"+value4+"',city='"+value5+"'";
            st = (PreparedStatement)conn.prepareStatement(sql);
            st.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(null, "Profile updated successfully");
            conn.close();
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_SaveProfile1ActionPerformed

    private void SearchWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchWithdrawActionPerformed
        
        try{
            conn=dbconnect.connectDb();
            String a = UsernameWithdraw.getText();
            System.out.println(a +"CustomerID String ");
            int b=Integer.parseInt(a);
           System.out.println(b +"CustomerID int ");
            String sql = "SELECT * FROM Balances WHERE CustomerID ="+b+"";
            st = (PreparedStatement)conn.prepareStatement(sql);
            //UsernameWithdraw.setText(""+rs.getString("CustomerID"));
            rs = st.executeQuery(sql);
            if(rs.next()){
                String add1 = rs.getString("FName");
                FullnameWithdraw.setText(add1);

                String add2 = rs.getString("Acc");
                AccnumWithdraw.setText(add2);

                String add3 = rs.getString("Balance");
                BalWithdraw.setText(add3);

                
            }
            else{
                JOptionPane.showMessageDialog(null,"Please enter correct Name");
            }
            conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SearchWithdrawActionPerformed

    private void CalculateWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateWithdrawActionPerformed
        try{
            String a1 = BalWithdraw.getText();
            int a = Integer.parseInt(a1);
            String a2 = AmountWithdraw.getText();
            int b = Integer.parseInt(a2);
            int sub = a-b;
            String sub1 = String.valueOf(sub);
            NewbalWithdraw.setText(sub1);
        }catch(Exception NumberFormatException){
            JOptionPane.showMessageDialog(null,"Please enter numbers only");
        }
        
    }//GEN-LAST:event_CalculateWithdrawActionPerformed

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
       try{
            String a1 = UsernameWithdraw.getText();
              System.out.println("Username : "+a1);
            int a = Integer.parseInt(a1);
            
            String a2 = NewbalWithdraw.getText();
            int b = Integer.parseInt(a2);
            System.out.println(""+b);
            conn=dbconnect.connectDb();
            String sql = "UPDATE Balances SET Balance = '" +b+ "' WHERE CustomerID = '" +a1+ "' ";
            st = (PreparedStatement)conn.prepareStatement(sql);
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Withdrawn Successfully.");

            UsernameWithdraw.setText("");
            FullnameWithdraw.setText("");
            AccnumWithdraw.setText("");
            BalWithdraw.setText("");
            AmountWithdraw.setText("");
            NewbalWithdraw.setText("");
            conn.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_WithdrawActionPerformed

    private void AccTransferPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_AccTransferPopupMenuWillBecomeInvisible
        try{
            conn=dbconnect.connectDb();
            String a1 = (String) AccTransfer.getSelectedItem();
            String sql = "SELECT * FROM Balances WHERE Acc = ?";
            st = conn.prepareStatement(sql);
            st.setString(1,a1);
            rs = st.executeQuery();
            if(rs.next()){
                String add = rs.getString("Balance");
                TransferNewInput.setText(add);
            }
            conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_AccTransferPopupMenuWillBecomeInvisible

    private void SearchTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTransferActionPerformed
        
        try{
            conn=dbconnect.connectDb();
            
            //UsernameTransfer.setText(""+rs.getString("CustomerID"));
            String a = UsernameTransfer.getText();
            
            int b=Integer.parseInt(a);
           
           String sql = "SELECT * FROM Balances WHERE CustomerID ="+b+"";
           st = conn.prepareStatement(sql);
            rs=st.executeQuery(sql);
            
            if(rs.next()){
                String add1 = rs.getString("FName");
                FullnameTransfer.setText(add1);

                String add2 = rs.getString("Acc");
                AccnumTransfer.setText(add2);

                String add3 = rs.getString("Balance");
                BalTransfer.setText(add3);

                
                
            }else{
                JOptionPane.showMessageDialog(null,"Please enter correct Name");
            }
            conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SearchTransferActionPerformed

    private void CalculateTransfer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateTransfer1ActionPerformed
        try{
            String a1 = BalTransfer.getText();
            String a2 = TransferInput.getText();
            int sum = Integer.parseInt(a1)-Integer.parseInt(a2);
            String sum1 = String.valueOf(sum);
            NewbalTransfer.setText(sum1);
        }catch(Exception NumberFormatException){
            JOptionPane.showMessageDialog(null,"Please enter numbers only");
        }
        
    }//GEN-LAST:event_CalculateTransfer1ActionPerformed

    private void CalculateTransfer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateTransfer2ActionPerformed
        try{
            String a1 = TransferInput.getText();
            String a2 = TransferNewInput.getText();
            int sum = Integer.parseInt(a1)+Integer.parseInt(a2);
            String sum1 = String.valueOf(sum);
            NewbalAccTransfer.setText(sum1);
        }catch(Exception NumberFormatException){
            JOptionPane.showMessageDialog(null,"Please enter numbers only for Transfer Amount");
        }
       
    }//GEN-LAST:event_CalculateTransfer2ActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        TransferD();
        TransferC();
        UsernameTransfer.setText("");
        FullnameTransfer.setText("");
        AccnumTransfer.setText("");
        BalTransfer.setText("");
        TransferInput.setText("");
        NewbalTransfer.setText("");
        TransferNewInput.setText("");
        NewbalAccTransfer.setText("");
        
    }//GEN-LAST:event_TransferActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            conn=dbconnect.connectDb();
           
            
            String a=UsernameTop.getText();
            System.out.println(a +"Userid String ");
            int b=Integer.parseInt(a);
           System.out.println(b +"Userid int "); 
            String sql = "SELECT * FROM Account WHERE CustomerID = "+b+"";
            st = (PreparedStatement)conn.prepareStatement(sql);
            
            
            rs = st.executeQuery();
            
            if (rs.next()){
                System.out.println("In menu class  in rs eecution");
                String add1 = rs.getString("FName");
                fname.setText(add1);
                
                String add2 = rs.getString("Acc");
                Accno.setText(add2);
                
                String add3 = rs.getString("DOB");
                DOB.setText(add3);
                
                String add4 = rs.getString("CustomerID");
                CustID.setText(add4);
                
                String add5 = rs.getString("Gender");
                gender.setText(add5);
                
                String add6 = rs.getString("city");
                city.setText(add6);
                
                String add7 = rs.getString("Mob");
                mobile.setText(add7);
                
                String add8 = rs.getString("Address");
                add.setText(add8);
                
                String add9 = rs.getString("LName");
                LName.setText(add9);
                
                String add10 = rs.getString("Email");
                email.setText(add10);
                
                String add11 = rs.getString("Balance");
                Balamt.setText(add11);
                
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Please enter correct Name");
            }
            conn.close();
            st.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TransferNewInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferNewInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferNewInputActionPerformed

    private void NewbalAccTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewbalAccTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewbalAccTransferActionPerformed

    private void AccTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccTransferActionPerformed
    
    
    //get accounts in database for transfer dropdownbox
    public void Account(){
        try{
            String sql = "SELECT * FROM Balances";
            st = conn.prepareStatement(sql);
            rs = st.executeQuery();
            while(rs.next()){
                String account = rs.getString("Acc");
                AccTransfer.addItem(account);
            }
            conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
 // transfer money from one account to another
 public void TransferC(){
     try{
        conn=dbconnect.connectDb();
         String value1 = (String) AccTransfer.getSelectedItem();
         
         String value2 = NewbalAccTransfer.getText();
         int b = Integer.parseInt(value2);
         String sql = "UPDATE Balances SET Balance = "+b+" WHERE Acc = '"+value1+"' ";
         st = conn.prepareStatement(sql);
         st.executeUpdate();
         JOptionPane.showMessageDialog(null,"Successfully transfered.");
         conn.close();
     }catch(Exception e){
         JOptionPane.showConfirmDialog(null, e);
     }
 }   
  // transfer money from one account to another
 public void TransferD(){
     try{
         conn=dbconnect.connectDb();
         String value1 = UsernameTransfer.getText();
         String value2 = NewbalTransfer.getText();
         int b = Integer.parseInt(value2);
         String sql = "UPDATE Balances SET Balance = " +b+ " WHERE CustomerID = '" +value1+ "' ";
         st = conn.prepareStatement(sql);
         st.executeUpdate();
         conn.close();
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AccTransfer;
    private javax.swing.JTextField Accno;
    private javax.swing.JTextField AccnumTransfer;
    private javax.swing.JTextField AccnumWithdraw;
    private javax.swing.JLabel AccnumtxtProfile1;
    private javax.swing.JLabel AccnumtxtTransfer;
    private javax.swing.JLabel AccnumtxtWithdraw;
    private javax.swing.JLabel AcctypetxtProfile1;
    private javax.swing.JLabel AddresstxtProfile1;
    private javax.swing.JTextField AmountWithdraw;
    private javax.swing.JLabel AmounttxtTransfer;
    private javax.swing.JLabel AmounttxtWithdraw;
    private javax.swing.JTextField BalTransfer;
    private javax.swing.JTextField BalWithdraw;
    private javax.swing.JTextField Balamt;
    private javax.swing.JLabel BaltxtTransfer;
    private javax.swing.JLabel BaltxtWithdraw;
    private javax.swing.JButton CalculateTransfer1;
    private javax.swing.JButton CalculateTransfer2;
    private javax.swing.JButton CalculateWithdraw;
    private javax.swing.JLabel CreditamounttxtTransfer;
    private javax.swing.JTextField CurrentDate;
    private javax.swing.JTextField CustID;
    private javax.swing.JTable Customers;
    private javax.swing.JTextField DOB;
    private javax.swing.JLabel DateofbirthtxtProfile1;
    public javax.swing.JButton EditProfile1;
    private javax.swing.JLabel EthnicitytxtProfile1;
    private javax.swing.JTextField FullnameTransfer;
    private javax.swing.JTextField FullnameWithdraw;
    private javax.swing.JLabel FullnametxtProfile1;
    private javax.swing.JLabel FullnametxtTransfer;
    private javax.swing.JLabel FullnametxtWithdraw;
    private javax.swing.JLabel GendertxtProfile1;
    private javax.swing.JTextField LName;
    private javax.swing.JLabel MobiletxtProfile1;
    private javax.swing.JTextField NewbalAccTransfer;
    private javax.swing.JTextField NewbalTransfer;
    private javax.swing.JTextField NewbalWithdraw;
    private javax.swing.JLabel NewbaltxtWithdraw;
    private javax.swing.JPanel ProfileTab1;
    private javax.swing.JPanel ProfileTab2;
    public javax.swing.JButton SaveProfile1;
    private javax.swing.JButton SearchTransfer;
    private javax.swing.JButton SearchWithdraw;
    private javax.swing.JButton Transfer;
    private javax.swing.JTextField TransferInput;
    private javax.swing.JTextField TransferNewInput;
    private javax.swing.JPanel TransferTab;
    private javax.swing.JLabel UnametxtTransfer;
    private javax.swing.JLabel UnametxtWithdraw;
    private javax.swing.JTextField UsernameTop;
    private javax.swing.JTextField UsernameTransfer;
    private javax.swing.JTextField UsernameWithdraw;
    private javax.swing.JButton Withdraw;
    private javax.swing.JTextField add;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField pin;
    // End of variables declaration//GEN-END:variables
}
